on:
  push:
    branches: [master]
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: Library-
      - uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          testMode: All
          customParameters: -nographics -assemblyNames com.anatawa12.test
